### ISSUE TITLE
provider-kubernetes: include models for all k8s builtin resources

### ISSUE THREAD

**Issue by Chewie** [upbound/upbound#2]
### What problem are you facing?

Along with remote cluster features, a common use-case of the provider-kubernetes is to generate wrapped builtin types like Deployment and Service.

The provider-kubernetes includes models for the apimachinera meta types, notably ObjectMeta, but nothing else. Ironically, we have models for every complex resource, except plain old kubernetes resources, which must be written with unstructured data.

### How could Upbound help solve your problem?

The embedded models could include all builtin k8s types, maybe by running datamodel-codegen on [k8s' openapi-spec](https://github.com/kubernetes/kubernetes/tree/master/api/openapi-spec/v3).

**Comment by cwilhit** [comment]
@Chewie I know this suggestion is in relation to how provider-kubernetes functions today. It's a good feedback. It spawned some thoughts around the general UX:

provider-kubernetes requires wrapping whichever objects you want to compose with `kind: object` such that you end up with a lot of boilerplate:

```yaml
apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: foo
spec:
  forProvider:
    manifest:
      apiVersion: v1
      data:
        sample-key: sample-value
      kind: ConfigMap
      metadata:
        namespace: default
  providerConfigRef:
    name: kubernetes-provider
```

Two ideas came to mind:

1. What if there was a more strongly typed provider-kubernetes that had high-fidelity representations of core Kubernetes APIs? The UX would look more like what this [provider-argocd](https://marketplace.upbound.io/providers/crossplane-contrib/provider-argocd/v0.9.2) does for the native Argo CD CRs
2.  Alternatively, maybe it would be nicer to just compose the Kubernetes objects with Crossplane directly. That has it's own challenges (such as no support for pointing at an external cluster context)

Curious to hear your thoughts.
